### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by NKID00** [A-Soul-Guide/A-Soul-Surfing-Guide#1]
[docs/贴吧论坛用语/闹挺大.md#来源](https://github.com/A-Soul-Guide/A-Soul-Surfing-Guide/blob/master/docs/%E8%B4%B4%E5%90%A7%E8%AE%BA%E5%9D%9B%E7%94%A8%E8%AF%AD/%E9%97%B9%E6%8C%BA%E5%A4%A7.md#%E6%9D%A5%E6%BA%90) 15 行

原*帖*不可*靠* -> 原**贴**不可**考**

<br/><br/><br/>

by 某一般路过anti（（

**Comment by Avimitin** [comment]
一般或许叫帖子应该没什么问题？

**Comment by Avimitin** [comment]
已在 [commit 3689728e](https://github.com/A-Soul-Guide/A-Soul-Surfing-Guide/commit/3689728e4a5e25b9b4aa48589020711eb72488ed) 修复
