### ISSUE TITLE
【错误报告】冲塔条目和内容不符合

### ISSUE THREAD

**Issue by Avimitin** [A-Soul-Guide/A-Soul-Surfing-Guide#2]
**描述错误**
[冲塔条目](https://wiki.asoul.org/v%E7%9B%B8%E5%85%B3%E7%94%A8%E8%AF%AD/%E5%86%B2%E5%A1%94) 的内容变成了 gachi 的内容。

**错误位置**
https://github.com/A-Soul-Guide/A-Soul-Surfing-Guide/blob/master/docs/v%E7%9B%B8%E5%85%B3%E7%94%A8%E8%AF%AD/%E5%86%B2%E5%A1%94.md

**正确的文本**
把标题改为 gachi

**附注**
无

**Comment by sakifore** [comment]
已修复
