### ISSUE TITLE
【错误报告】梁木页面大标题错误

### ISSUE THREAD

**Issue by 7est** [A-Soul-Guide/A-Soul-Surfing-Guide#3]
**描述错误**
梁木页面大标题为SC

**错误位置**
https://wiki.asoul.org/v%E7%9B%B8%E5%85%B3%E7%94%A8%E8%AF%AD/%E6%A2%81%E6%9C%A8

**正确的文本**
把标题改为梁木

**附注**
无

**Comment by Avimitin** [comment]
Fixed in commit [b42b2c5eb23196465d18b69b5dddbbd9ece8d558](https://github.com/A-Soul-Guide/A-Soul-Surfing-Guide/commit/b42b2c5eb23196465d18b69b5dddbbd9ece8d558#diff-0d4ee0b13f4b43f6440da5e2ca168540f96505b276d02518d04db84067d7936b)
