### ISSUE TITLE
【错误报告】直球宣传小团体是否😅

### ISSUE THREAD

**Issue by AlexKanawha** [A-Soul-Guide/A-Soul-Surfing-Guide#4]
**描述错误**
清晰明了的描述文档的错误。
/直播二创相关/相关团体列表

**错误位置**
请告诉我们错误在哪个位置。
相关团体列表

**正确的文本**
请告诉我们正确的文本应该是什么。
qq小团体🙅‍

**附注**
关于这个错误还有什么别的备注的。
无

**Comment by Avimitin** [comment]
不好意思我们没有注意到 QQ 群的问题。我先去问一下内容编辑者的意见，如果他同意的话我就删掉这部分内容。

**Comment by AlexKanawha** [comment]
> 不好意思我们没有注意到 QQ 群的问题。我先去问一下内容编辑者的意见，如果他同意的话我就删掉这部分内容。QQ 群这么敏感的吗，如果不支持的宣传话我之后写进内容编辑要求里。

是的，反对小团体一直是主流共识

**Comment by Avimitin** [comment]
> > 不好意思我们没有注意到 QQ 群的问题。我先去问一下内容编辑者的意见，如果他同意的话我就删掉这部分内容。QQ 群这么敏感的吗，如果不支持的宣传话我之后写进内容编辑要求里。
> 
> 是的，反对小团体一直是主流共识

好的，但是目前我只是负责网页构建，我不能自己专断，所以关于内容还得等我联系上另一位开发者商量过后才能做决定。
