### ISSUE TITLE
【新条目】

### ISSUE THREAD

**Issue by qianxi0410** [A-Soul-Guide/A-Soul-Surfing-Guide#7]
### 梗名字

寄了

### 来源

上古起源于游戏界的一句GOOD GAME，缩写为GG，一般用作游戏结束时称赞对手。中文谐音梗来自于LOL知名主播♿otto♿，在游戏快输/局势不好的时候一般说 「寄了」、「这把已经寄了」。后来由另一个主播炫神🐕将其发扬光大，经常在游戏不顺的时候，大喊一句「寄！」。

### 语义

事物完了，结束了。中性词，一般用于调侃。

**Comment by Avimitin** [comment]
cc @sakifore
如果你没空的话就我来写
